name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PAYSTACK_SECRET_KEY: ${{secrets.PAYSTACK_SECRET_KEY}}

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo clippy && cargo build --verbose
      - name: Run tests
        run: cargo test -- --nocapture
